// Personal Copyright
#pragma once
#include "Logging/LogMacros.h"

WARFIRSTPERSON_API DECLARE_LOG_CATEGORY_EXTERN(LogWar, Log, All);
WARFIRSTPERSON_API DECLARE_LOG_CATEGORY_EXTERN(LogWarAnimation, Log, All);
WARFIRSTPERSON_API DECLARE_LOG_CATEGORY_EXTERN(LogWarInput, Log, All);
WARFIRSTPERSON_API DECLARE_LOG_CATEGORY_EXTERN(LogWarInventory, Log, All);
WARFIRSTPERSON_API DECLARE_LOG_CATEGORY_EXTERN(LogWarTeam, Log, All);
WARFIRSTPERSON_API DECLARE_LOG_CATEGORY_EXTERN(LogWarWeapon, Log, All);